import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menus = [
  {
    label: "Home",
    route: "/",
    button:false
  },
  {
    label: "Blog",
    route: "/blog",
    button:false
  },
  {
    label: "Contact",
    route: "/contact-us",
    button:false
  },
  {
    label: "Login",
    route: "/login",
    button:false
  },
  {
    label: "Registration",
    route: "/sign-up",
    button:true
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white sticky shadow-lg left-0 top-0 w-full py-6 flex justify-between items-center px-[10%]">
          <Link href="/" className="text-2xl font-bold">The Site Logo</Link>
          <div className="flex gap-10 items-center">
            {menus.map((item, index) => (
              <Link
                className={item.button ? "rounded p-5 bg-amber-800 hover:bg-blue-950 hover:text-shadow-amber-50":""}
                href={item.route}
                key={index}
              >
                {item.label}
              </Link>
            ))}
          </div>
        </nav>
        <div className="px-[10%] py-16">{children}</div>
        <footer className="flex h-[450px] justify-center items-center bg-black text-white text-3xl">My Footer</footer>
      </body>
    </html>
  );
}
