import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menus = [
  {
    label: "Home",
    route: "/",
  },
  {
    label: "Login",
    route: "/login",
  },
  {
    label: "Registration",
    route: "/sign-up",
  },
  {
    label: "Contact",
    route: "/contact-us",
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white sticky shadow-lg left-0 top-0 w-full py-6 flex justify-between items-center">
          <h1>The Site Logo</h1>
          <div className="flex">
            {menus.map((item, index) => (
              <Link
                className="hover:bg-amber-400 p-3"
                href={item.route}
                key={index}
              >
                {item.label}
              </Link>
            ))}
          </div>
        </nav>
        {children}
        <footer>My Footer</footer>
      </body>
    </html>
  );
}
