import Image from "next/image";
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  
  return (
    <>
     <div>
      This is HomePage
        <Image
            aria-hidden
            src="/next.svg"
            //alt="next icon"
            width={160}
            height={70}
          />
     </div>
    </>
  );
}
