import HomeComponent from "@/components/HomeComponent";
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  
  return (
    <>
    <HomeComponent />
    </>
  );
}
